name: Deploy to Staging

on:
  # Automatic trigger when pushing tags
  # push:
  #   branches:
  #     - "!*"
  #   tags:
  #     - 'v*'
  workflow_run:
    workflows: ["build"]
    type:
      - complete

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          # Add your deployment script/commands here
          echo "deploy stage"
